# Generated by Django 3.2.7 on 2021-10-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_counter', '0002_alter_tagcounter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcounter',
            name='tags',
            field=models.JSONField(default=dict, null=True, verbose_name='URL Tags'),
        ),
    ]
