# Generated by Django 3.2.7 on 2021-10-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_counter', '0003_alter_tagcounter_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcounter',
            name='status',
            field=models.CharField(choices=[('performed', 'Performed'), ('done', 'Done'), ('error', 'Error')], default='performed', max_length=9, verbose_name='Parse status'),
        ),
    ]
